CREATE TABLE "letter_templates" (
        "id" serial PRIMARY KEY NOT NULL,
        "title" varchar(200) NOT NULL,
        "scenario_description" text NOT NULL,
        "category" varchar(100) NOT NULL,
        "tags" text[] DEFAULT '{}' NOT NULL,
        "letter_type" "letter_type" NOT NULL,
        "prefill_data" jsonb NOT NULL,
        "active" boolean DEFAULT true NOT NULL,
        "sort_order" integer DEFAULT 0 NOT NULL,
        "contextual_notes" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "letter_requests" ADD COLUMN "template_id" integer;--> statement-breakpoint
CREATE INDEX "idx_letter_templates_active" ON "letter_templates" USING btree ("active");--> statement-breakpoint
CREATE INDEX "idx_letter_templates_letter_type" ON "letter_templates" USING btree ("letter_type");--> statement-breakpoint
CREATE INDEX "idx_letter_templates_sort_order" ON "letter_templates" USING btree ("sort_order");--> statement-breakpoint
ALTER TABLE "letter_requests" ADD CONSTRAINT "letter_requests_template_id_letter_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."letter_templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
INSERT INTO "letter_templates" ("title", "scenario_description", "category", "tags", "letter_type", "prefill_data", "active", "sort_order") VALUES
  ('Unpaid Invoice', 'You completed work or delivered goods/services but the other party has not paid the agreed amount despite the payment being due.', 'Unpaid Money', ARRAY['invoice','payment','debt','services'], 'demand-letter', '{"subject":"Demand for Payment of Unpaid Invoice","description":"I completed work/delivered goods as agreed, but the other party has failed to pay the outstanding invoice despite the payment being past due.","desiredOutcome":"Full payment of the outstanding invoice amount plus any applicable late fees or interest.","tonePreference":"firm","letterType":"demand-letter"}', true, 10),
  ('Security Deposit Return', 'Your landlord has not returned your security deposit after you moved out, or has made improper deductions from it.', 'Property Damage', ARRAY['security deposit','landlord','tenant','rental'], 'landlord-tenant', '{"subject":"Demand for Return of Security Deposit","description":"I vacated the rental property and left it in good condition. My landlord has failed to return my security deposit within the legally required timeframe.","desiredOutcome":"Full return of the security deposit, or an itemized statement of any lawful deductions with the remaining balance returned.","tonePreference":"firm","letterType":"landlord-tenant"}', true, 20),
  ('Property Damage Claim', 'Someone else''s actions (or negligence) caused damage to your property — vehicle, home, personal belongings, etc.', 'Property Damage', ARRAY['property damage','negligence','compensation','repair'], 'demand-letter', '{"subject":"Demand for Compensation for Property Damage","description":"The other party''s actions or negligence caused damage to my property, and I am seeking compensation for the cost of repair or replacement.","desiredOutcome":"Full compensation for repair or replacement costs, including any related expenses.","tonePreference":"firm","letterType":"demand-letter"}', true, 30),
  ('Defective Product Refund', 'You purchased a product that turned out to be defective, broken, or not as described, and the seller has refused a refund or replacement.', 'Services Not Rendered', ARRAY['defective product','refund','consumer','warranty'], 'consumer-complaint', '{"subject":"Demand for Refund for Defective Product","description":"I purchased a product that was defective/not as described. Despite contacting the seller, they have refused to provide a refund or replacement.","desiredOutcome":"Full refund of the purchase price, or a replacement product that meets the original specifications.","tonePreference":"moderate","letterType":"consumer-complaint"}', true, 40),
  ('Breach of Service Agreement', 'A service provider failed to deliver the services they were contracted to perform, or performed them in a substandard manner.', 'Services Not Rendered', ARRAY['breach of contract','services','agreement','performance'], 'contract-breach', '{"subject":"Notice of Breach of Service Agreement","description":"The service provider failed to deliver the contracted services as agreed, or the services provided were substantially below the agreed-upon standard.","desiredOutcome":"Completion of the contracted services as originally agreed, or a full refund of amounts paid.","tonePreference":"firm","letterType":"contract-breach"}', true, 50),
  ('Debt Collection — Outstanding Balance', 'Someone owes you money — whether from a personal loan, business transaction, or other agreement — and has not repaid despite requests.', 'Unpaid Money', ARRAY['debt collection','outstanding balance','loan','repayment'], 'debt-collection', '{"subject":"Demand for Payment of Outstanding Debt","description":"The debtor owes me money from a prior agreement/transaction and has failed to make payment despite previous requests.","desiredOutcome":"Full repayment of the outstanding balance within 30 days.","tonePreference":"firm","letterType":"debt-collection"}', true, 60),
  ('Insurance Claim Denial Appeal', 'Your insurance company denied a legitimate claim, offered an unfairly low settlement, or is unreasonably delaying payment.', 'Unpaid Money', ARRAY['insurance','claim denial','appeal','settlement'], 'insurance-dispute', '{"subject":"Appeal of Insurance Claim Denial","description":"My insurance claim was denied or undervalued despite being a legitimate, covered claim under my policy. I am requesting a review and reconsideration.","desiredOutcome":"Reversal of the claim denial and full payment of the covered amount, or a fair settlement offer.","tonePreference":"moderate","letterType":"insurance-dispute"}', true, 70),
  ('Personal Injury — Accident Demand', 'You were injured due to someone else''s negligence (car accident, slip and fall, etc.) and are seeking compensation for medical bills, lost wages, and pain/suffering.', 'Property Damage', ARRAY['personal injury','accident','medical bills','negligence'], 'personal-injury-demand', '{"subject":"Demand for Compensation for Personal Injury","description":"I sustained injuries due to the other party''s negligence. I am seeking compensation for medical expenses, lost wages, and pain and suffering.","desiredOutcome":"Fair compensation covering all medical expenses, lost wages, and damages for pain and suffering.","tonePreference":"firm","letterType":"personal-injury-demand"}', true, 80)
ON CONFLICT DO NOTHING;