import { dispatchToWorker, buildEmailHtml, buildPlainText, sendWithRetry, APP_NAME } from "../../core";

/**
 * Notify subscriber that their letter draft is now available to view.
 * This email is sent 24 hours after submission, once the AI pipeline has
 * completed and the draft is ready for review.
 *
 * The draft is NOT attorney-reviewed. Clicking the CTA opens the letter page
 * where the full ai_draft is rendered with a DRAFT watermark and disabled
 * text selection. The primary action is "Submit For Attorney Review".
 */
export async function sendFreePreviewReadyEmail(opts: {
  to: string;
  name: string;
  subject: string;
  letterId: number;
  appUrl: string;
  letterType?: string;
  jurisdictionState?: string;
  aiDraftPreview?: string; // Optional: short preview snippet of the draft
}) {
  const dispatched = await dispatchToWorker({ type: "free_preview_ready", ...opts });
  if (dispatched) return;

  const ctaUrl = `${opts.appUrl}/letters/${opts.letterId}?preview=1`;
  const letterTypeLabel = opts.letterType
    ? opts.letterType.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
    : "Legal Letter";
  const jurisdictionLine = opts.jurisdictionState
    ? `<p style="margin:0 0 6px;font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;"><strong>Jurisdiction:</strong> ${opts.jurisdictionState}</p>`
    : "";

  // DRAFT watermark styling for email
  const draftWatermark = `
    <div style="position:relative; background:#FFFBEB; border:2px dashed #D97706; border-radius:12px; padding:24px; margin:20px 0; text-align:center;">
      <div style="position:absolute; top:50%; left:50%; transform:translate(-50%, -50%) rotate(-15deg); font-family:Inter,Arial,sans-serif; font-size:48px; font-weight:900; color:rgba(217,119,6,0.15); text-transform:uppercase; letter-spacing:4px; pointer-events:none;">
        DRAFT
      </div>
      <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:14px;color:#92400E;font-weight:700;">📄 Draft Preview — Not Yet Attorney Reviewed</p>
      <p style="margin:8px 0 0;font-family:Inter,Arial,sans-serif;font-size:13px;color:#78350F;">This document has been generated by AI and has not been reviewed, edited, or approved by a licensed attorney.</p>
    </div>
  `;

  // Legal letterhead header
  const legalLetterhead = `
    <div style="border-bottom:3px solid #0F2744; padding-bottom:16px; margin-bottom:24px;">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td style="vertical-align:middle;">
            <p style="margin:0;font-family:Georgia,serif;font-size:22px;font-weight:700;color:#0F2744;letter-spacing:-0.5px;">Talk To My Lawyer</p>
            <p style="margin:4px 0 0;font-family:Inter,Arial,sans-serif;font-size:12px;color:#6B7280;letter-spacing:1px;text-transform:uppercase;">Professional Legal Document Services</p>
          </td>
          <td style="vertical-align:middle; text-align:right;">
            <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:11px;color:#9CA3AF;">Document ID: #${opts.letterId}</p>
            <p style="margin:4px 0 0;font-family:Inter,Arial,sans-serif;font-size:11px;color:#9CA3AF;">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </td>
        </tr>
      </table>
    </div>
  `;

  const body = `
    ${legalLetterhead}
    <p>Hello ${opts.name},</p>
    <p>Your letter draft is ready for review. You can now read the complete draft and decide whether to submit it for licensed attorney review and formal signature.</p>

    ${draftWatermark}

    <!-- Letter summary card -->
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
      style="background:#F9FAFB;border:1px solid #E5E7EB;border-radius:10px;margin:20px 0;">
      <tr><td style="padding:20px;">
        <p style="margin:0 0 6px;font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;"><strong>Subject:</strong> ${opts.subject}</p>
        <p style="margin:0 0 6px;font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;"><strong>Type:</strong> ${letterTypeLabel}</p>
        ${jurisdictionLine}
        <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;"><strong>Letter ID:</strong> #${opts.letterId}</p>
      </td></tr>
    </table>

    ${opts.aiDraftPreview ? `
    <!-- Draft snippet preview -->
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
      style="background:#FFFFFF;border:1px solid #E5E7EB;border-radius:10px;margin:20px 0;">
      <tr><td style="padding:20px;">
        <p style="margin:0 0 10px;font-family:Inter,Arial,sans-serif;font-size:12px;color:#9CA3AF;text-transform:uppercase;letter-spacing:1px;">Preview of your draft</p>
        <p style="margin:0;font-family:Georgia,serif;font-size:14px;color:#1F2937;line-height:1.6;font-style:italic;">${opts.aiDraftPreview}</p>
      </td></tr>
    </table>
    ` : ""}

    <!-- What you get -->
    <p style="margin:0 0 12px;font-family:Inter,Arial,sans-serif;font-size:15px;font-weight:700;color:#0F2744;">What you get with attorney review:</p>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-bottom:16px;">
      <tr>
        <td width="28" valign="top" style="padding:4px 8px 8px 0;font-size:16px;">⚖️</td>
        <td style="font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;padding-bottom:8px;">
          <strong>Licensed attorney review</strong> — reviewed, edited, and approved before you send it
        </td>
      </tr>
      <tr>
        <td width="28" valign="top" style="padding:4px 8px 8px 0;font-size:16px;">📑</td>
        <td style="font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;padding-bottom:8px;">
          <strong>Professional PDF</strong> delivered to your account, formatted and ready to send
        </td>
      </tr>
      <tr>
        <td width="28" valign="top" style="padding:4px 8px 8px 0;font-size:16px;">🔒</td>
        <td style="font-family:Inter,Arial,sans-serif;font-size:14px;color:#374151;">
          <strong>Jurisdiction-specific</strong> — researched and drafted for your state
        </td>
      </tr>
    </table>

    <!-- Strong CTA for attorney review -->
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
      style="background:#0F2744;border-radius:10px;margin:20px 0;">
      <tr><td style="padding:20px; text-align:center;">
        <p style="margin:0 0 8px;font-family:Inter,Arial,sans-serif;font-size:16px;font-weight:700;color:#FFFFFF;">Ready to make it official?</p>
        <p style="margin:0 0 16px;font-family:Inter,Arial,sans-serif;font-size:13px;color:#E5E7EB;">Submit your draft for attorney review and receive a professionally signed legal document.</p>
        <a href="${ctaUrl}" style="display:inline-block;background:#FFFFFF;color:#0F2744;font-family:Inter,Arial,sans-serif;font-size:14px;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;">Submit for Attorney Review →</a>
      </td></tr>
    </table>

    <!-- Disclaimer -->
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
      style="background:#EFF6FF;border:1px solid #BFDBFE;border-radius:8px;margin:0 0 8px;">
      <tr><td style="padding:14px 18px;">
        <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:13px;color:#1D4ED8;">
          <strong>Important:</strong> This draft is provided as-is and has not been reviewed by an attorney. Do not rely on it as legal advice or send it without attorney review and formal signature.
        </p>
      </td></tr>
    </table>

    <!-- Legal letterhead footer -->
    <div style="border-top:1px solid #E5E7EB; padding-top:16px; margin-top:24px;">
      <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:11px;color:#9CA3AF;text-align:center;">
        Talk To My Lawyer — Professional Legal Document Services<br>
        This is an automated notification. Please do not reply directly to this email.
      </p>
    </div>
  `;

  const html = buildEmailHtml({
    preheader: `Your letter draft is ready to preview — complete draft, not yet attorney-reviewed.`,
    title: "Your Letter Draft Is Ready",
    body,
    ctaText: "View My Draft",
    ctaUrl,
    accentColor: "#0F2744",
  });

  await sendWithRetry({
    to: opts.to,
    subject: `[${APP_NAME}] Your letter draft is ready for review`,
    html,
    text: buildPlainText({
      title: "Your Letter Draft Is Ready",
      body:
        `Hello ${opts.name},\n\n` +
        `Your letter draft "${opts.subject}" (Letter #${opts.letterId}) is ready for review.\n\n` +
        `[ D R A F T — NOT YET ATTORNEY REVIEWED ]\n\n` +
        `This draft has been generated by AI and has not been reviewed by an attorney. You can read the full draft, then decide whether to submit it for licensed attorney review.\n\n` +
        `To submit it for attorney review, visit:\n${ctaUrl}\n\n` +
        `Attorney review includes:\n- Licensed attorney review, edits, and approval\n- Professional PDF delivered to your account\n- Jurisdiction-specific\n\n` +
        `Click below to view your draft.`,
      ctaText: "View My Draft",
      ctaUrl,
    }),
  });
}
