// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-layouts/DarkPrestige.tsx": () => import("../components/mockups/homepage-layouts/DarkPrestige.tsx"),
  "./components/mockups/homepage-layouts/EditorialColumns.tsx": () => import("../components/mockups/homepage-layouts/EditorialColumns.tsx"),
  "./components/mockups/homepage-layouts/KineticBold.tsx": () => import("../components/mockups/homepage-layouts/KineticBold.tsx"),
  "./components/mockups/homepage-layouts/SplitHero.tsx": () => import("../components/mockups/homepage-layouts/SplitHero.tsx"),
  "./components/mockups/homepage-layouts/StackedImpact.tsx": () => import("../components/mockups/homepage-layouts/StackedImpact.tsx")
};
