apiVersion: v1
kind: ConfigMap
metadata:
  name: ttml-config
  namespace: ttml
data:
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ALLOWED_ORIGINS: "http://ttml.local"
  APP_URL: "http://ttml.local"
