apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttml-ingress
  namespace: ttml
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ttml.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ttml-backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ttml-frontend
                port:
                  number: 80
